# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ latest ]
  pull_request:
    branches: [ latest ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  prisma_day_2021:
    runs-on: ubuntu-latest
    container: node:14.18.1-bullseye
    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: prisma_day_2021_latest
          POSTGRES_PASSWORD: change_me_in_multiple_places
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout application
        uses: actions/checkout@v2
      - name: Install application
        run: |
          
          apt-get update
          apt-get install --yes postgresql-client
      
          psql -h postgres -d $APPNAME -U postgres_user -c 'SELECT 1;

          DATABASE_URL="postgres://$KEYSTONE_USERNAME:$PGPASSWORD@db/$APPNAME"

          cd $GITHUB_WORKSPACE
          yarn        
          yarn dev &         
          sleep 5   
          echo "Building unseeded production server: $APPNAME"       
          yarn site:build          
          echo "Build unseeded $appname:latest production succeded" 

        env:
          PGPASSWORD: change_me_in_multiple_places
          KEYSTONE_USERNAME: postgres_user
          APPNAME: prisma_day_2021_latest
          KEYSTONE_NEXTJS_BUILD_API_KEY: keystone_change_me2
      # Deploy:
